In [5]:
import pandas as pd
import numpy as np

In [7]:
df=pd.read_csv('IPL_Batter.csv')
df

,Player Name,Team,Runs,Matches,Inn,No,HS,AVG,BF,SR,100s,50s,4s,6s
0,Sai Sudharsan,GT,759,15,15,1,108*,54.21,486,156.17,1,6,88,21
1,Surya Kumar Yadav,MI,717,16,16,5,73*,65.18,427,167.91,0,5,69,38
2,Virat Kohli,RCB,657,15,15,3,73*,54.75,454,144.71,0,8,66,19
3,Shubman Gill,GT,650,15,15,2,93*,50.00,417,155.87,0,6,62,24
4,Mitchell Marsh,LSG,627,13,13,0,117,48.23,383,163.70,1,6,56,37
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
151,Khaleel Ahmed,CSK,1,14,2,2,1*,-,2,50.00,0,0,0,0
152,Mohit Sharma,DC,1,8,2,1,1*,1.00,3,33.33,0,0,0,0
153,Donovan Ferreira,DC,1,1,1,0,1,1.00,3,33.33,0,0,0,0
154,Digvesh Singh,LSG,1,13,2,1,1,1.00,3,33.33,0,0,0,0
155,Manoj Bhandage,RCB,1,1,1,0,1,1.00,4,25.00,0,0,0,0

In [10]:
#1
df.info()
df.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 156 entries, 0 to 155
Data columns (total 14 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Player Name  156 non-null    object
 1   Team         156 non-null    object
 2   Runs         156 non-null    int64
 3   Matches      156 non-null    int64
 4   Inn          156 non-null    int64
 5   No           156 non-null    int64
 6   HS           156 non-null    object
 7   AVG          156 non-null    object
 8   BF           156 non-null    int64
 9   SR           156 non-null    float64
 10  100s         156 non-null    int64
 11  50s          156 non-null    int64
 12  4s           156 non-null    int64
 13  6s           156 non-null    int64
dtypes: float64(1), int64(9), object(4)
memory usage: 17.2+ KB

,Player Name,Team,Runs,Matches,Inn,No,HS,AVG,BF,SR,100s,50s,4s,6s
0,Sai Sudharsan,GT,759,15,15,1,108*,54.21,486,156.17,1,6,88,21
1,Surya Kumar Yadav,MI,717,16,16,5,73*,65.18,427,167.91,0,5,69,38
2,Virat Kohli,RCB,657,15,15,3,73*,54.75,454,144.71,0,8,66,19
3,Shubman Gill,GT,650,15,15,2,93*,50.00,417,155.87,0,6,62,24
4,Mitchell Marsh,LSG,627,13,13,0,117,48.23,383,163.70,1,6,56,37

,Player Name,Team,Runs,Matches,Inn,No,HS,AVG,BF,SR,100s,50s,4s,6s
0,Sai Sudharsan,GT,759,15,15,1,108*,54.21,486,156.17,1,6,88,21
1,Surya Kumar Yadav,MI,717,16,16,5,73*,65.18,427,167.91,0,5,69,38
2,Virat Kohli,RCB,657,15,15,3,73*,54.75,454,144.71,0,8,66,19
3,Shubman Gill,GT,650,15,15,2,93*,50.00,417,155.87,0,6,62,24
4,Mitchell Marsh,LSG,627,13,13,0,117,48.23,383,163.70,1,6,56,37

In [11]:
#2 display the  last five rows
df.tail()

,Player Name,Team,Runs,Matches,Inn,No,HS,AVG,BF,SR,100s,50s,4s,6s
151,Khaleel Ahmed,CSK,1,14,2,2,1*,-,2,50.00,0,0,0,0
152,Mohit Sharma,DC,1,8,2,1,1*,1.00,3,33.33,0,0,0,0
153,Donovan Ferreira,DC,1,1,1,0,1,1.00,3,33.33,0,0,0,0
154,Digvesh Singh,LSG,1,13,2,1,1,1.00,3,33.33,0,0,0,0
155,Manoj Bhandage,RCB,1,1,1,0,1,1.00,4,25.00,0,0,0,0

In [12]:
#find the number of rows and columns
df.shape

(156, 14)

In [15]:
#4display column names
df.columns

Index(['Player Name', 'Team', 'Runs', 'Matches', 'Inn', 'No', 'HS', 'AVG',
       'BF', 'SR', '100s', '50s', '4s', '6s'],
      dtype='object')

In [17]:
#5display data types
df.dtypes

Player Name     object
Team            object
Runs             int64
Matches          int64
Inn              int64
No               int64
HS              object
AVG             object
BF               int64
SR             float64
100s             int64
50s              int64
4s               int64
6s               int64
dtype: object

In [18]:
#7 generate summary statistics
df.describe()

,Runs,Matches,Inn,No,BF,SR,100s,50s,4s,6s
count,156.000000,156.000000,156.000000,156.000000,156.000000,156.000000,156.000000,156.000000,156.000000,156.000000
mean,161.320513,9.865385,7.153846,1.634615,105.673077,134.394103,0.057692,0.916667,14.391026,8.294872
std,180.352772,4.757455,4.810142,1.658163,112.191838,57.237148,0.233912,1.590124,17.778774,9.515500
min,1.000000,1.000000,1.000000,0.000000,1.000000,25.000000,0.000000,0.000000,0.000000,0.000000
25%,10.750000,6.000000,2.750000,0.000000,12.000000,100.000000,0.000000,0.000000,1.000000,0.000000
50%,93.500000,11.000000,6.000000,1.000000,63.500000,140.005000,0.000000,0.000000,7.000000,4.000000
75%,254.250000,14.000000,12.000000,3.000000,164.750000,162.707500,0.000000,1.000000,23.000000,14.000000
max,759.000000,17.000000,17.000000,7.000000,486.000000,400.000000,1.000000,8.000000,88.000000,40.000000

In [22]:
#8 missing values 
df.isnull().sum()

Player Name    0
Team           0
Runs           0
Matches        0
Inn            0
No             0
HS             0
AVG            0
BF             0
SR             0
100s           0
50s            0
4s             0
6s             0
dtype: int64

In [26]:
#display only the name of the columns
df["Player Name"]

0          Sai Sudharsan
1      Surya Kumar Yadav
2            Virat Kohli
3           Shubman Gill
4         Mitchell Marsh
             ...
151        Khaleel Ahmed
152         Mohit Sharma
153     Donovan Ferreira
154        Digvesh Singh
155       Manoj Bhandage
Name: Player Name, Length: 156, dtype: object

In [28]:
#10 display name,runs and matches columns
df[["Player Name","Runs","Matches"]]

           Player Name  Runs  Matches
0        Sai Sudharsan   759       15
1    Surya Kumar Yadav   717       16
2          Virat Kohli   657       15
3         Shubman Gill   650       15
4       Mitchell Marsh   627       13
..                 ...   ...      ...
151      Khaleel Ahmed     1       14
152       Mohit Sharma     1        8
153   Donovan Ferreira     1        1
154      Digvesh Singh     1       13
155     Manoj Bhandage     1        1

[156 rows x 3 columns]

In [31]:
#11 Find names with more runs
df[df["Runs"]>100]

,Player Name,Team,Runs,Matches,Inn,No,HS,AVG,BF,SR,100s,50s,4s,6s
0,Sai Sudharsan,GT,759,15,15,1,108*,54.21,486,156.17,1,6,88,21
1,Surya Kumar Yadav,MI,717,16,16,5,73*,65.18,427,167.91,0,5,69,38
2,Virat Kohli,RCB,657,15,15,3,73*,54.75,454,144.71,0,8,66,19
3,Shubman Gill,GT,650,15,15,2,93*,50.00,417,155.87,0,6,62,24
4,Mitchell Marsh,LSG,627,13,13,0,117,48.23,383,163.70,1,6,56,37
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
70,Vijay Shankar,CSK,118,6,5,2,69*,39.33,91,129.67,0,1,8,3
71,Sam Curran,CSK,114,5,5,0,88,22.80,84,135.71,0,1,11,4
72,Liam Livingstone,RCB,112,10,8,1,54,16.00,84,133.33,0,1,4,9
73,Krunal Pandya,RCB,109,15,7,1,73*,18.17,86,126.74,0,1,9,4
74,Shubham Dubey,RR,106,9,8,4,34*,26.50,66,160.60,0,0,6,8

In [33]:
#12 players from csk
df[df["Team"] == "CSK"]

,Player Name,Team,Runs,Matches,Inn,No,HS,AVG,BF,SR,100s,50s,4s,6s
22,Shivam Dube,CSK,357,14,14,3,50,32.45,270,132.22,0,1,22,21
30,Ravindra Jadeja,CSK,301,14,14,5,77*,33.44,222,135.58,0,2,25,10
43,Ayush Mhatre,CSK,240,7,7,0,94,34.29,127,188.97,0,1,31,11
47,Dewald Brevis,CSK,225,6,6,0,57,37.50,125,180.00,0,2,13,17
54,MS Dhoni,CSK,196,14,13,5,30*,24.50,145,135.17,0,0,12,12
55,Rachin Ravindra,CSK,191,8,8,1,65*,27.29,149,128.18,0,1,18,4
62,Devon Conway,CSK,156,6,6,0,69,26.00,119,131.09,0,2,17,4
68,Ruturaj Gaikwad,CSK,122,5,5,0,63,24.40,81,150.61,0,2,14,4
70,Vijay Shankar,CSK,118,6,5,2,69*,39.33,91,129.67,0,1,8,3
71,Sam Curran,CSK,114,5,5,0,88,22.80,84,135.71,0,1,11,4
83,Shaik Rasheed,CSK,71,5,5,0,27,14.20,63,112.69,0,0,9,2
85,Urvil Patel,CSK,68,3,3,0,37,22.67,32,212.50,0,0,5,6
92,Rahul Tripathi,CSK,55,5,5,0,23,11.00,57,96.49,0,0,6,1
99,Ravichandran Ashwin,CSK,33,9,4,0,13,8.25,30,110.00,0,0,3,1
100,Deepak Hooda,CSK,31,7,5,0,22,6.20,41,75.60,0,0,2,1
109,Jamie Overton,CSK,15,3,2,2,11*,-,7,214.28,0,0,1,1
110,Anshul Kamboj,CSK,14,8,5,3,5*,7.00,12,116.66,0,0,2,0
128,Noor Ahmad,CSK,7,14,6,2,2*,1.75,17,41.17,0,0,0,0
151,Khaleel Ahmed,CSK,1,14,2,2,1*,-,2,50.00,0,0,0,0

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 156 entries, 0 to 155
Data columns (total 14 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Player Name  156 non-null    object
 1   Team         156 non-null    object
 2   Runs         156 non-null    int64
 3   Matches      156 non-null    int64
 4   Inn          156 non-null    int64
 5   No           156 non-null    int64
 6   HS           156 non-null    object
 7   AVG          156 non-null    object
 8   BF           156 non-null    int64
 9   SR           156 non-null    float64
 10  100s         156 non-null    int64
 11  50s          156 non-null    int64
 12  4s           156 non-null    int64
 13  6s           156 non-null    int64
dtypes: float64(1), int64(9), object(4)
memory usage: 17.2+ KB

In [44]:
#13find the player with more number of matches 
df[df["Matches"]>=15]

,Player Name,Team,Runs,Matches,Inn,No,HS,AVG,BF,SR,100s,50s,4s,6s
0,Sai Sudharsan,GT,759,15,15,1,108*,54.21,486,156.17,1,6,88,21
1,Surya Kumar Yadav,MI,717,16,16,5,73*,65.18,427,167.91,0,5,69,38
2,Virat Kohli,RCB,657,15,15,3,73*,54.75,454,144.71,0,8,66,19
3,Shubman Gill,GT,650,15,15,2,93*,50.00,417,155.87,0,6,62,24
5,Shreyas Iyer,PBKS,604,17,17,5,97*,50.33,345,175.07,0,6,43,39
7,Prabhsimran Singh,PBKS,549,17,17,0,91,32.29,342,160.52,0,4,56,30
12,Priyansh Arya,PBKS,475,17,17,0,103,27.94,265,179.24,1,2,55,25
15,Rohit Sharma,MI,418,15,15,1,81,29.86,280,149.28,0,4,41,22
21,Nehal Wadhera,PBKS,369,16,15,3,70,30.75,253,145.84,0,2,28,21
24,Shashank Singh,PBKS,350,17,14,7,61*,50.00,228,153.50,0,3,23,18
25,N Tilak Varma,MI,343,16,13,2,59,31.18,248,138.30,0,2,23,16
28,Rajat Patidar,RCB,312,15,14,1,64,24.00,217,143.77,0,2,25,14
38,Jitesh Sharma,RCB,261,15,11,4,85*,37.29,148,176.35,0,1,24,17
40,Naman Dhir,MI,252,16,12,4,46,31.50,138,182.60,0,0,24,13
48,Hardik Pandya,MI,224,15,12,3,48*,24.89,137,163.50,0,0,18,12
58,Shahrukh Khan,GT,179,15,11,5,57,29.83,100,179.00,0,1,11,13
73,Krunal Pandya,RCB,109,15,7,1,73*,18.17,86,126.74,0,1,9,4
75,Rahul Tewatia,GT,99,15,12,4,24*,12.38,59,167.79,0,0,6,7
96,Rashid Khan,GT,40,15,8,3,12,8.00,28,142.85,0,0,2,3
134,Sai Kishore,GT,5,15,3,0,3,1.67,10,50.00,0,0,0,0
138,Yash Dayal,RCB,4,15,3,1,3,2.00,8,50.00,0,0,0,0
141,Mohammed Siraj,GT,3,15,1,1,3*,-,4,75.00,0,0,0,0
145,Trent Boult,MI,2,16,2,1,1*,2.00,3,66.66,0,0,0,0
147,Arshdeep Singh,PBKS,2,17,2,1,1*,2.00,6,33.33,0,0,0,0

In [48]:
#14display inn more than 10
df[df["Inn"]>= 10]

,Player Name,Team,Runs,Matches,Inn,No,HS,AVG,BF,SR,100s,50s,4s,6s
0,Sai Sudharsan,GT,759,15,15,1,108*,54.21,486,156.17,1,6,88,21
1,Surya Kumar Yadav,MI,717,16,16,5,73*,65.18,427,167.91,0,5,69,38
2,Virat Kohli,RCB,657,15,15,3,73*,54.75,454,144.71,0,8,66,19
3,Shubman Gill,GT,650,15,15,2,93*,50.00,417,155.87,0,6,62,24
4,Mitchell Marsh,LSG,627,13,13,0,117,48.23,383,163.70,1,6,56,37
5,Shreyas Iyer,PBKS,604,17,17,5,97*,50.33,345,175.07,0,6,43,39
6,Yashasvi Jaiswal,RR,559,14,14,1,75,43.00,350,159.71,0,6,60,28
7,Prabhsimran Singh,PBKS,549,17,17,0,91,32.29,342,160.52,0,4,56,30
8,K L Rahul,DC,539,13,13,3,112*,53.90,360,149.72,1,3,52,21
9,Jos Buttler,GT,538,14,13,4,97*,59.78,330,163.03,0,5,52,24
10,Nicholas Pooran,LSG,524,14,14,2,87*,43.67,267,196.25,0,5,45,40
11,Heinrich Klaasen,SRH,487,13,13,2,105*,44.27,282,172.69,1,1,42,25
12,Priyansh Arya,PBKS,475,17,17,0,103,27.94,265,179.24,1,2,55,25
13,Aiden Markram,LSG,445,13,13,0,66,34.23,299,148.82,0,5,38,22
14,Abhishek Sharma,SRH,439,14,13,0,141,33.77,227,193.39,1,2,46,28
15,Rohit Sharma,MI,418,15,15,1,81,29.86,280,149.28,0,4,41,22
16,Phil Salt,RCB,403,13,13,1,65,33.58,229,175.98,0,4,48,22
17,Riyan Parag,RR,393,14,14,2,95,32.75,236,166.52,0,1,27,27
18,Ajinkya Rahane,KKR,390,13,12,1,61,35.45,264,147.72,0,3,36,20
19,Ryan Rickelton,MI,388,14,14,1,62*,29.85,257,150.97,0,3,47,17
20,Travis Head,SRH,374,13,12,0,76,31.17,230,162.60,0,3,50,15
21,Nehal Wadhera,PBKS,369,16,15,3,70,30.75,253,145.84,0,2,28,21
22,Shivam Dube,CSK,357,14,14,3,50,32.45,270,132.22,0,1,22,21
23,Ishan Kishan,SRH,354,14,13,3,106*,35.40,232,152.58,1,1,33,15
24,Shashank Singh,PBKS,350,17,14,7,61*,50.00,228,153.50,0,3,23,18
25,N Tilak Varma,MI,343,16,13,2,59,31.18,248,138.30,0,2,23,16
26,Dhruv Jurel,RR,333,14,13,4,70,37.00,213,156.33,0,2,22,22
27,Ayush Badoni,LSG,329,14,11,1,74,32.90,222,148.19,0,2,27,14
28,Rajat Patidar,RCB,312,15,14,1,64,24.00,217,143.77,0,2,25,14
29,Abishek Porel,DC,301,13,13,1,51,25.08,205,146.82,0,1,28,12
30,Ravindra Jadeja,CSK,301,14,14,5,77*,33.44,222,135.58,0,2,25,10
31,Tristan Stubbs,DC,300,14,13,7,41*,50.00,199,150.75,0,0,25,11
32,Angkrish Raghuvanshi,KKR,300,12,11,2,50,33.33,215,139.53,0,1,30,8
33,Sherfane Rutherford,GT,291,13,11,2,46,32.33,185,157.29,0,0,22,18
35,Josh Inglis,PBKS,278,11,11,2,73,30.89,171,162.57,0,1,26,16
36,Rishabh Pant,LSG,269,14,13,2,118*,24.45,202,133.16,1,1,23,16
37,Axar Patel,DC,263,12,11,1,43,26.30,167,157.48,0,0,23,15
38,Jitesh Sharma,RCB,261,15,11,4,85*,37.29,148,176.35,0,1,24,17
40,Naman Dhir,MI,252,16,12,4,46,31.50,138,182.60,0,0,24,13
41,Devdutt Padikkal,RCB,247,10,10,1,61,27.44,164,150.60,0,2,21,14
42,Sunil Narine,KKR,246,12,12,1,44,22.36,144,170.83,0,0,25,19
44,Shimron Hetmyer,RR,239,14,13,2,52,21.73,164,145.73,0,1,17,11
45,Aniket Verma,SRH,236,14,12,3,74,26.22,142,166.19,0,1,12,20
46,Will Jacks,MI,233,13,11,1,53,23.30,172,135.46,0,1,22,11
48,Hardik Pandya,MI,224,15,12,3,48*,24.89,137,163.50,0,0,18,12
49,Nitish Rana,RR,217,11,11,1,81,21.70,134,161.94,0,2,27,9
50,Rinku Singh,KKR,206,13,11,4,38*,29.43,134,153.73,0,0,20,10
54,MS Dhoni,CSK,196,14,13,5,30*,24.50,145,135.17,0,0,12,12
57,Nitish Kumar Reddy,SRH,182,13,11,3,32,22.75,153,118.95,0,0,16,4
58,Shahrukh Khan,GT,179,15,11,5,57,29.83,100,179.00,0,1,11,13
59,Andre Russell,KKR,167,13,10,1,57*,18.56,102,163.72,0,1,16,14
60,Abdul Samad,LSG,164,13,12,4,45,20.50,93,176.34,0,0,8,14
61,Marcus Stoinis,PBKS,160,13,11,5,44*,26.67,86,186.04,0,0,8,15
63,David Miller,LSG,153,11,11,6,27*,30.60,120,127.50,0,0,13,4
75,Rahul Tewatia,GT,99,15,12,4,24*,12.38,59,167.79,0,0,6,7

In [49]:
#15display player with 100s
df[df["100s"] == 1]

,Player Name,Team,Runs,Matches,Inn,No,HS,AVG,BF,SR,100s,50s,4s,6s
0,Sai Sudharsan,GT,759,15,15,1,108*,54.21,486,156.17,1,6,88,21
4,Mitchell Marsh,LSG,627,13,13,0,117,48.23,383,163.70,1,6,56,37
8,K L Rahul,DC,539,13,13,3,112*,53.90,360,149.72,1,3,52,21
11,Heinrich Klaasen,SRH,487,13,13,2,105*,44.27,282,172.69,1,1,42,25
12,Priyansh Arya,PBKS,475,17,17,0,103,27.94,265,179.24,1,2,55,25
14,Abhishek Sharma,SRH,439,14,13,0,141,33.77,227,193.39,1,2,46,28
23,Ishan Kishan,SRH,354,14,13,3,106*,35.40,232,152.58,1,1,33,15
36,Rishabh Pant,LSG,269,14,13,2,118*,24.45,202,133.16,1,1,23,16
39,Vaibhav Suryavanshi,RR,252,7,7,0,101,36.00,122,206.55,1,1,18,24

In [50]:
#16total count of the player
len(df)

156

In [52]:
#17 count of team player SRH
(df["Team"]== "SRH").sum()

np.int64(14)

In [53]:
#18 count of team player KKR
(df["Team"]== "KKR").sum()

np.int64(15)

In [54]:
#19 max runs
df["Runs"].max()

759

In [55]:
#20 min runs
df["Runs"].min()

1

In [56]:
#21 average runs
df["Runs"].mean()

np.float64(161.32051282051282)

In [57]:
#22 median 
df["Runs"].median()

93.5

In [58]:
#23highest runs made by the player
df[df["Runs"]==df["Runs"].max()]

,Player Name,Team,Runs,Matches,Inn,No,HS,AVG,BF,SR,100s,50s,4s,6s
0,Sai Sudharsan,GT,759,15,15,1,108*,54.21,486,156.17,1,6,88,21

In [60]:
#24lowest runs made by the player
df[df["Runs"]==df["Runs"].min()]

,Player Name,Team,Runs,Matches,Inn,No,HS,AVG,BF,SR,100s,50s,4s,6s
148,Varun Chakaravarthy,KKR,1,13,1,1,1*,-,1,100.00,0,0,0,0
149,V Satyanarayana Penmetsa,MI,1,2,1,1,1*,-,1,100.00,0,0,0,0
150,Karn Sharma,MI,1,6,1,1,1*,-,1,100.00,0,0,0,0
151,Khaleel Ahmed,CSK,1,14,2,2,1*,-,2,50.00,0,0,0,0
152,Mohit Sharma,DC,1,8,2,1,1*,1.00,3,33.33,0,0,0,0
153,Donovan Ferreira,DC,1,1,1,0,1,1.00,3,33.33,0,0,0,0
154,Digvesh Singh,LSG,1,13,2,1,1,1.00,3,33.33,0,0,0,0
155,Manoj Bhandage,RCB,1,1,1,0,1,1.00,4,25.00,0,0,0,0

In [63]:
#25player having bf less than 10
df[df["BF"]<=10]

,Player Name,Team,Runs,Matches,Inn,No,HS,AVG,BF,SR,100s,50s,4s,6s
105,Kusal Mendis,GT,20,1,1,0,20,20.00,10,200.00,0,0,1,2
109,Jamie Overton,CSK,15,3,2,2,11*,-,7,214.28,0,0,1,1
113,Atharva Taide,SRH,13,1,1,0,13,13.00,9,144.44,0,0,3,0
117,Mohammad Shami,SRH,10,9,4,3,6*,10.00,10,100.00,0,0,1,0
120,Kagiso Rabada,GT,9,4,2,1,7*,9.00,8,112.50,0,0,0,1
121,Shahbaz Ahmed,LSG,9,3,1,0,9,9.00,8,112.50,0,0,1,0
124,Kwena Maphaka,RR,8,2,1,1,8*,-,2,400.00,0,0,2,0
125,Raj Angad Bawa,MI,8,3,1,1,8*,-,4,200.00,0,0,0,0
126,Tushar Deshpande,RR,7,10,4,3,3,7.00,8,87.50,0,0,0,0
129,Akash Deep,LSG,6,6,2,1,6*,6.00,2,300.00,0,0,0,1
130,Sandeep Sharma,RR,6,10,1,1,6*,-,5,120.00,0,0,0,0
131,Mitchell Starc,DC,6,11,6,4,2*,3.00,10,60.00,0,0,0,0
133,Rovman Powell,KKR,5,2,1,0,5,5.00,5,100.00,0,0,1,0
134,Sai Kishore,GT,5,15,3,0,3,1.67,10,50.00,0,0,0,0
135,Prince Yadav,LSG,5,6,2,2,4*,-,10,50.00,0,0,0,0
137,Lockie Ferguson,PBKS,4,4,1,1,4*,-,1,400.00,0,0,1,0
138,Yash Dayal,RCB,4,15,3,1,3,2.00,8,50.00,0,0,0,0
139,Akash Madhwal,RR,4,4,1,1,4*,-,9,44.44,0,0,0,0
140,Madhav Tiwari,DC,3,1,1,0,3,3.00,4,75.00,0,0,0,0
141,Mohammed Siraj,GT,3,15,1,1,3*,-,4,75.00,0,0,0,0
142,Kumar Kartikeya Singh,RR,3,4,2,0,2,1.50,5,60.00,0,0,0,0
143,Simarjeet Singh,SRH,3,4,3,1,3*,1.50,7,42.85,0,0,0,0
144,Fazalhaq Farooqi,RR,2,5,1,1,2*,-,2,100.00,0,0,0,0
145,Trent Boult,MI,2,16,2,1,1*,2.00,3,66.66,0,0,0,0
146,Spencer Johnson,KKR,2,4,2,2,1*,-,4,50.00,0,0,0,0
147,Arshdeep Singh,PBKS,2,17,2,1,1*,2.00,6,33.33,0,0,0,0
148,Varun Chakaravarthy,KKR,1,13,1,1,1*,-,1,100.00,0,0,0,0
149,V Satyanarayana Penmetsa,MI,1,2,1,1,1*,-,1,100.00,0,0,0,0
150,Karn Sharma,MI,1,6,1,1,1*,-,1,100.00,0,0,0,0
151,Khaleel Ahmed,CSK,1,14,2,2,1*,-,2,50.00,0,0,0,0
152,Mohit Sharma,DC,1,8,2,1,1*,1.00,3,33.33,0,0,0,0
153,Donovan Ferreira,DC,1,1,1,0,1,1.00,3,33.33,0,0,0,0
154,Digvesh Singh,LSG,1,13,2,1,1,1.00,3,33.33,0,0,0,0
155,Manoj Bhandage,RCB,1,1,1,0,1,1.00,4,25.00,0,0,0,0

In [64]:
#26 sort according to the inns
df.sort_values(by="Inn")

,Player Name,Team,Runs,Matches,Inn,No,HS,AVG,BF,SR,100s,50s,4s,6s
155,Manoj Bhandage,RCB,1,1,1,0,1,1.00,4,25.00,0,0,0,0
102,Sediqullah Atal,DC,22,1,1,0,22,22.00,16,137.50,0,0,0,2
105,Kusal Mendis,GT,20,1,1,0,20,20.00,10,200.00,0,0,1,2
111,Matthew Breetzke,LSG,14,1,1,0,14,14.00,12,116.66,0,0,1,1
113,Atharva Taide,SRH,13,1,1,0,13,13.00,9,144.44,0,0,3,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
0,Sai Sudharsan,GT,759,15,15,1,108*,54.21,486,156.17,1,6,88,21
1,Surya Kumar Yadav,MI,717,16,16,5,73*,65.18,427,167.91,0,5,69,38
12,Priyansh Arya,PBKS,475,17,17,0,103,27.94,265,179.24,1,2,55,25
7,Prabhsimran Singh,PBKS,549,17,17,0,91,32.29,342,160.52,0,4,56,30
5,Shreyas Iyer,PBKS,604,17,17,5,97*,50.33,345,175.07,0,6,43,39

In [70]:
#27 player with more number of matches and 100s
df[(df["Matches"]>= 15 ) & (df["100s"]==1)]

,Player Name,Team,Runs,Matches,Inn,No,HS,AVG,BF,SR,100s,50s,4s,6s
0,Sai Sudharsan,GT,759,15,15,1,108*,54.21,486,156.17,1,6,88,21
12,Priyansh Arya,PBKS,475,17,17,0,103,27.94,265,179.24,1,2,55,25

In [71]:
#df.sort_values(by="Inn") in descending
df.sort_values(by="Inn",ascending=False)

,Player Name,Team,Runs,Matches,Inn,No,HS,AVG,BF,SR,100s,50s,4s,6s
12,Priyansh Arya,PBKS,475,17,17,0,103,27.94,265,179.24,1,2,55,25
7,Prabhsimran Singh,PBKS,549,17,17,0,91,32.29,342,160.52,0,4,56,30
5,Shreyas Iyer,PBKS,604,17,17,5,97*,50.33,345,175.07,0,6,43,39
1,Surya Kumar Yadav,MI,717,16,16,5,73*,65.18,427,167.91,0,5,69,38
21,Nehal Wadhera,PBKS,369,16,15,3,70,30.75,253,145.84,0,2,28,21
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
105,Kusal Mendis,GT,20,1,1,0,20,20.00,10,200.00,0,0,1,2
116,Xavier Bartlett,PBKS,11,4,1,0,11,11.00,15,73.33,0,0,1,0
102,Sediqullah Atal,DC,22,1,1,0,22,22.00,16,137.50,0,0,0,2
133,Rovman Powell,KKR,5,2,1,0,5,5.00,5,100.00,0,0,1,0
155,Manoj Bhandage,RCB,1,1,1,0,1,1.00,4,25.00,0,0,0,0

In [73]:
#29 TOP 2-Player
df.nlargest(2,"Matches")

,Player Name,Team,Runs,Matches,Inn,No,HS,AVG,BF,SR,100s,50s,4s,6s
5,Shreyas Iyer,PBKS,604,17,17,5,97*,50.33,345,175.07,0,6,43,39
7,Prabhsimran Singh,PBKS,549,17,17,0,91,32.29,342,160.52,0,4,56,30

In [74]:
#30 bottom 2-Player
df.nsmallest(2,"Matches")

,Player Name,Team,Runs,Matches,Inn,No,HS,AVG,BF,SR,100s,50s,4s,6s
102,Sediqullah Atal,DC,22,1,1,0,22,22.00,16,137.5,0,0,0,2
105,Kusal Mendis,GT,20,1,1,0,20,20.00,10,200.0,0,0,1,2

In [75]:
#31 count of player in each team
df["Team"].value_counts()

Team
CSK     19
RR      17
DC      17
MI      16
LSG     15
PBKS    15
KKR     15
GT      14
RCB     14
SRH     14
Name: count, dtype: int64

In [76]:
#32 average matches by team
df.groupby("Team")["Matches"].mean()

Team
CSK      8.052632
DC       8.764706
GT      11.142857
KKR      9.266667
LSG     10.333333
MI      10.312500
PBKS    11.733333
RCB     10.642857
RR       9.470588
SRH      9.714286
Name: Matches, dtype: float64

In [77]:
#33 Count player by their 50s 
df.groupby("50s").size()

50s
0    94
1    30
2    14
3     5
4     3
5     4
6     5
8     1
dtype: int64

In [79]:
df["50s"].value_counts()

50s
0    94
1    30
2    14
6     5
3     5
5     4
4     3
8     1
Name: count, dtype: int64

In [80]:
#34 Average SR by Team
df.groupby("Team")["SR"].mean()

Team
CSK     130.346842
DC      119.012941
GT      142.952857
KKR     123.555333
LSG     140.846667
MI      137.221250
PBKS    144.912667
RCB     141.392857
RR      137.220000
SRH     129.773571
Name: SR, dtype: float64

In [81]:
#35 Maximum SR by Team
df.groupby("Team")["SR"].max()

Team
CSK     214.28
DC      179.74
GT      200.00
KKR     170.83
LSG     300.00
MI      200.00
PBKS    400.00
RCB     291.66
RR      400.00
SRH     193.39
Name: SR, dtype: float64

In [82]:
#36 Minimum HS by Team
df.groupby("Team")["HS"].min()

Team
CSK       1*
DC         1
GT      108*
KKR       1*
LSG        1
MI        1*
PBKS      1*
RCB        1
RR       101
SRH     105*
Name: HS, dtype: object

In [84]:
#37 rename columns
df.rename(columns={
    "No":"Number",
    "Runs":"Runns"
})

,Player Name,Team,Runns,Matches,Inn,Number,HS,AVG,BF,SR,100s,50s,4s,6s
0,Sai Sudharsan,GT,759,15,15,1,108*,54.21,486,156.17,1,6,88,21
1,Surya Kumar Yadav,MI,717,16,16,5,73*,65.18,427,167.91,0,5,69,38
2,Virat Kohli,RCB,657,15,15,3,73*,54.75,454,144.71,0,8,66,19
3,Shubman Gill,GT,650,15,15,2,93*,50.00,417,155.87,0,6,62,24
4,Mitchell Marsh,LSG,627,13,13,0,117,48.23,383,163.70,1,6,56,37
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
151,Khaleel Ahmed,CSK,1,14,2,2,1*,-,2,50.00,0,0,0,0
152,Mohit Sharma,DC,1,8,2,1,1*,1.00,3,33.33,0,0,0,0
153,Donovan Ferreira,DC,1,1,1,0,1,1.00,3,33.33,0,0,0,0
154,Digvesh Singh,LSG,1,13,2,1,1,1.00,3,33.33,0,0,0,0
155,Manoj Bhandage,RCB,1,1,1,0,1,1.00,4,25.00,0,0,0,0

In [86]:
#38 add runs percentage
df["Runs Percentage"]=df["Runs"]*0.10
df["Runs Percentage"]

0      75.9
1      71.7
2      65.7
3      65.0
4      62.7
       ...
151     0.1
152     0.1
153     0.1
154     0.1
155     0.1
Name: Runs Percentage, Length: 156, dtype: float64

In [94]:
#39 5% of macthes
df["Percent of BF"] = df["BF"] *0.05
df["Percent of BF"]

0      24.30
1      21.35
2      22.70
3      20.85
4      19.15
       ...
151     0.10
152     0.15
153     0.15
154     0.15
155     0.20
Name: Percent of BF, Length: 156, dtype: float64

In [ ]:
#40