In [2]:
import pandas as pd
import numpy as np

In [3]:
data=pd.read_csv('diamond.csv')
data

       carat        cut color clarity  depth  table  price     x     y     z
0       0.23      Ideal     E     SI2   61.5   55.0    326  3.95  3.98  2.43
1       0.21    Premium     E     SI1   59.8   61.0    326  3.89  3.84  2.31
2       0.23       Good     E     VS1   56.9   65.0    327  4.05  4.07  2.31
3       0.29    Premium     I     VS2   62.4   58.0    334  4.20  4.23  2.63
4       0.31       Good     J     SI2   63.3   58.0    335  4.34  4.35  2.75
...      ...        ...   ...     ...    ...    ...    ...   ...   ...   ...
53935   0.72      Ideal     D     SI1   60.8   57.0   2757  5.75  5.76  3.50
53936   0.72       Good     D     SI1   63.1   55.0   2757  5.69  5.75  3.61
53937   0.70  Very Good     D     SI1   62.8   60.0   2757  5.66  5.68  3.56
53938   0.86    Premium     H     SI2   61.0   58.0   2757  6.15  6.12  3.74
53939   0.75      Ideal     D     SI2   62.2   55.0   2757  5.83  5.87  3.64

[53940 rows x 10 columns]

In [11]:
d1=pd.DataFrame({'ID':[1,2,3,5],
                'class':[9,10,11,12]})
d1

   ID  class
0   1      9
1   2     10
2   3     11
3   5     12

In [13]:
d2=pd.DataFrame({'ID':[1,2,3,4],
                 'Name':['A','B','C','D']})
d2

   ID Name
0   1    A
1   2    B
2   3    C
3   4    D

In [10]:
pd.merge(d1,d2, on ='ID')

   ID  class Name
0   1      9    A
1   2     10    B
2   3     11    C

In [17]:
n1=pd.merge(d1,d2, how='inner',on='ID')
n1

   ID  class Name
0   1      9    A
1   2     10    B
2   3     11    C

In [20]:
n2=pd.merge(d1,d2, how='left',on='ID')
n2

   ID  class Name
0   1      9    A
1   2     10    B
2   3     11    C
3   5     12  NaN

In [22]:
n3=pd.merge(d1,d2, how='right',on='ID')
n3

   ID  class Name
0   1    9.0    A
1   2   10.0    B
2   3   11.0    C
3   4    NaN    D

In [23]:
n4=pd.merge(d1,d2, how='outer',on='ID')
n4

   ID  class Name
0   1    9.0    A
1   2   10.0    B
2   3   11.0    C
3   4    NaN    D
4   5   12.0  NaN

In [46]:
df_1=pd.DataFrame({'ID':[1,2,3,5],
                'class':[9,10,11,12]},index=[11,22,32,44])
df_1

    ID  class
11   1      9
22   2     10
32   3     11
44   5     12

In [47]:
df_2=pd.DataFrame({'ID':[1,2,3,4],
                 'Name':['A','B','C','D']},index=[11,22,33,44])
df_2

    ID Name
11   1    A
22   2    B
33   3    C
44   4    D

In [51]:
pd.merge(df_1,df_2, how='inner',on='ID')

   ID  class Name
0   1      9    A
1   2     10    B
2   3     11    C

In [53]:
pd.merge(df_1,df_2, left_index=True,right_index=True)

    ID_x  class  ID_y Name
11     1      9     1    A
22     2     10     2    B
44     5     12     4    D

In [58]:
data={
    'Age':[25,np.nan,30,22,np.nan],
    'Score':[85,90,np.nan,75,80],
    'City':['New York',np.nan,'Paris','London','Paris'],
}
dataf=pd.DataFrame(data)
print("Original DataFrame:\n",dataf)

Original DataFrame:
     Age  Score      City
0  25.0   85.0  New York
1   NaN   90.0       NaN
2  30.0    NaN     Paris
3  22.0   75.0    London
4   NaN   80.0     Paris

# detecting missing values

In [60]:
dataf.isnull()

     Age  Score   City
0  False  False  False
1   True  False   True
2  False   True  False
3  False  False  False
4   True  False  False

In [61]:
dataf.isnull().sum()

Age      2
Score    1
City     1
dtype: int64

In [62]:
dataf.notnull()

     Age  Score   City
0   True   True   True
1  False   True  False
2   True  False   True
3   True   True   True
4  False   True   True

In [69]:
df_clean_rows=dataf.dropna()
df_clean_cols=dataf.dropna(axis=1)
df_clean_subset=dataf.dropna(subset=['Age'])

In [66]:

df_clean_rows

Empty DataFrame
Columns: []
Index: [0, 1, 2, 3, 4]

In [70]:
df_clean_cols

Empty DataFrame
Columns: []
Index: [0, 1, 2, 3, 4]

In [71]:
df_clean_subset

    Age  Score      City
0  25.0   85.0  New York
2  30.0    NaN     Paris
3  22.0   75.0    London

In [72]:
df_zero=dataf.fillna(0)
df_zero

    Age  Score      City
0  25.0   85.0  New York
1   0.0   90.0         0
2  30.0    0.0     Paris
3  22.0   75.0    London
4   0.0   80.0     Paris

In [80]:
dataf['Age']=dataf['Age'].fillna(dataf['Age'].mean())
dataf['Age']

0    25.000000
1    25.666667
2    30.000000
3    22.000000
4    25.666667
Name: Age, dtype: float64

In [85]:
dataf['City']=dataf['City'].fillna(dataf['City'].mode()[0])
dataf['City']

0    New York
1       Paris
2       Paris
3      London
4       Paris
Name: City, dtype: object

# Time-series interpolation

In [87]:
df_ffill=dataf.ffill
df_bfill=dataf.bfill